Completely randomized betting simulator, no logic is applied to which games are bet on.

In [52]:
import pandas as pd
from scripts.simulator import SimRandom

SimRandom = SimRandom(bet_value = 100, win_rate = 0.66, num_games = 1200)
SimRandom.calculate()
SimRandom.return_data()

,Date,Time,Away,A-Pts,Home,H-Pts,OT,SeasonID,MOV,Spread,O/U,A_ML,ML_Payout,H_ML,Bet_Status,Value
0,2009-10-28,10:30p,Phoenix Suns,109,Los Angeles Clippers,107,,2009-10,-2.0,2.5,189,105.0,105.0,-125.0,1,95.238095
1,2010-03-22,8:00p,San Antonio Spurs,99,Oklahoma City Thunder,96,,2009-10,-3.0,188,2,-120.0,-120.0,100.0,0,-100.000000
2,2010-01-26,10:00p,Golden State Warriors,96,Sacramento Kings,99,,2009-10,3.0,199.5,5,-200.0,170.0,170.0,0,-100.000000
3,2007-11-09,8:00p,Denver Nuggets,118,Washington Wizards,92,,2007-08,-26.0,198.5,1,-105.0,-105.0,-115.0,1,95.238095
4,2021-01-18,3:00p,San Antonio Spurs,125,Portland Trail Blazers,104,,2020-21,-21.0,221.5,2.5,-175.0,-175.0,155.0,1,57.142857
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,2015-03-10,8:30p,Toronto Raptors,107,San Antonio Spurs,117,,2014-15,10.0,6.5,193.5,220.0,-270.0,-270.0,1,37.037037
1196,2007-12-18,7:30p,Sacramento Kings,106,New Jersey Nets,101,,2007-08,-5.0,8.5,205.5,415.0,415.0,-515.0,1,24.096386
1197,2017-12-15,7:00p,Oklahoma City Thunder,119,Philadelphia 76ers,117,3OT,2017-18,-2.0,8,214.5,240.0,240.0,-280.0,1,41.666667
1198,2009-12-01,9:00p,Golden State Warriors,107,Denver Nuggets,135,,2009-10,28.0,11,199.5,550.0,-750.0,-750.0,1,13.333333
1199,2019-04-07,7:30p,Washington Wizards,110,New York Knicks,113,,2018-19,3.0,3,206.5,135.0,-155.0,-155.0,1,64.516129

In [53]:
SimRandom.return_totals()

(39028.6769078001, -39100.0, -71.32309219989838, -0.9981758799948875)

In [63]:
SimRandom.reroll()
SimRandom.calculate()
SimRandom.return_totals()

(39485.504805657416, -35800.0, 3685.504805657416, -1.1029470616105423)

In [64]:
SimRandom.return_data()

,Date,Time,Away,A-Pts,Home,H-Pts,OT,SeasonID,MOV,Spread,O/U,A_ML,ML_Payout,H_ML,Bet_Status,Value
0,2011-03-21,7:00p,Orlando Magic,97,Cleveland Cavaliers,86,,2010-11,-11.0,12,221,885.0,885.0,-1350.0,0,-100.000000
1,2019-03-27,8:00p,Portland Trail Blazers,118,Chicago Bulls,98,,2018-19,-20.0,7.5,215,250.0,250.0,-310.0,0,-100.000000
2,2012-12-10,10:00p,Toronto Raptors,74,Portland Trail Blazers,92,,2012-13,18.0,9,187.5,320.0,-400.0,-400.0,1,25.000000
3,2016-02-06,5:00p,Portland Trail Blazers,96,Houston Rockets,79,,2015-16,-17.0,5,188.5,210.0,210.0,-250.0,1,47.619048
4,2015-12-22,7:00p,Memphis Grizzlies,104,Philadelphia 76ers,90,,2015-16,-14.0,4,209,115.0,115.0,-135.0,0,-100.000000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,2016-03-14,10:30p,Cleveland Cavaliers,85,Utah Jazz,94,,2015-16,9.0,4,189,200.0,-235.0,-235.0,1,42.553191
1196,2008-02-02,8:30p,Houston Rockets,91,Milwaukee Bucks,83,,2007-08,-8.0,pk,186.5,-165.0,-165.0,145.0,1,60.606061
1197,2015-01-13,9:00p,Golden State Warriors,116,Utah Jazz,105,,2014-15,-11.0,6.5,199.5,200.0,200.0,-240.0,1,50.000000
1198,2022-04-23,4:30p,Dallas Mavericks,99,Utah Jazz,100,,2021-22,1.0,3,223.5,155.0,-175.0,-175.0,1,57.142857
1199,2017-10-28,9:00p,Los Angeles Lakers,81,Utah Jazz,96,,2017-18,15.0,2,207,100.0,-120.0,-120.0,1,83.333333

In [66]:
SimRandom.worst_losses()

,Date,Time,Away,A-Pts,Home,H-Pts,OT,SeasonID,MOV,Spread,O/U,A_ML,ML_Payout,H_ML,Bet_Status,Value
0,2008-04-06,3:30p,Dallas Mavericks,105,Phoenix Suns,98,,2007-08,-7.0,15.5,211,2000.0,2000.0,-3000.0,0,-100.0
1,2016-01-20,8:00p,Detroit Pistons,123,Houston Rockets,114,,2015-16,-9.0,15.5,216.5,1910.0,1910.0,-7123.0,0,-100.0
2,2013-03-29,10:00p,Utah Jazz,105,Portland Trail Blazers,95,,2012-13,-10.0,14.5,203.5,1520.0,1520.0,-3320.0,0,-100.0
3,2015-03-02,7:00p,Toronto Raptors,114,Philadelphia 76ers,103,,2014-15,-11.0,15,211.5,1410.0,1410.0,-3010.0,0,-100.0
4,2018-05-06,3:30p,Golden State Warriors,118,New Orleans Pelicans,92,,2017-18,-26.0,14,222,1300.0,1300.0,-3500.0,0,-100.0